### ISSUE TITLE
PreRelease v4.3.0 Bosh

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-bosh#22]
- [x] Bump PR from release branch to 4.3
  - [x] Test 4.3 branch

**Comment by teddytpc1** [comment]
The TAR files are being created and will be uploaded to the dev Bucket in order to perform validations.

**Comment by teddytpc1** [comment]
The Bosh deployment was tested. An error was thrown. It is related to `clusterd`. It is not starting:
```
2021/12/06 15:40:42 DEBUG: [Cluster] [Main] Removing '/var/ossec/queue/cluster/'.
2021/12/06 15:40:42 DEBUG: [Cluster] [Main] Removed '/var/ossec/queue/cluster/'.
2021/12/06 15:40:44 ERROR: [Cluster] [Main] Unhandled exception: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 199, in <module>
    asyncio.run(main_function(args, cluster_configuration, cluster_items, main_logger))
  File "/var/ossec/framework/python/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 72, in master_main
    from wazuh.core.cluster import master, local_server
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/master.py", line 23, in <module>
    from wazuh.core.cluster.dapi import dapi
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 34, in <module>
    process_pool = ProcessPoolExecutor(max_workers=1)
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 642, in __init__
    self._call_queue = _SafeQueue(
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```
If the option -r is added (to start it with root), the daemon starts:
`./wazuh-clusterd -r`

**Comment by teddytpc1** [comment]
Some additional tests were executed yesterday. A `chown wazuh:wazuh` command was executed recursively in `/var/ossec` but the issue persists.

**Comment by teddytpc1** [comment]
The pre-start script for Manager and Worker deployments. The following line was added to resolve the wazuh-clusterd issue:
`chmod 777 /dev/shm`

This was tested and it is working fine. Branch name is: `22-4.3-configs`

**Comment by teddytpc1** [comment]
Some configurations were made in order to fix some deprecated tags in ossec.conf. Everything is working properly.
PR was created.
